name: "Prettier"

on:
  push:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  merge_group:
  workflow_dispatch:

jobs:
  prettier-check:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - name: Download repo
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js v20.15.0
        uses: actions/setup-node@v5
        with:
          node-version: "20.15.0"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Check code with Prettier
        run: pnpm exec prettier --check .
