name: Update Crowdin strings bi-directionally

run-name: Update from Crowdin

on:
  schedule:
    - cron: "30 */3 * * *"
  push:
    branches-ignore:
      - i18n-crowdin-translations
      - manual-crowdin-updates
      - gh-readonly-queue/**
      - dependabot/**
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-from-crowdin:
    name: Update strings from Crowdin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: "main"

      - name: Grab strings from Crowdin
        if: github.triggering_actor != 'support+bot@crowdin.com' && github.triggering_actor != 'actions@github.com'
        uses: crowdin/github-action@v2.3.0
        with: # This part can be a little fragile, be careful!
          upload_sources: true
          upload_translations: false
          upload_language: en
          download_sources: false
          download_translations: true
          skip_untranslated_strings: false
          source: i18n/lang/en-US.json
          translation: i18n/lang/%locale%.json
          export_only_approved: false
          localization_branch_name: i18n-crowdin-translations
          create_pull_request: true
          commit_message: "i18n: new Crowdin strings"
          pull_request_title: (Crowdin Action) New translation strings
          pull_request_body: New translated strings are now available!
          pull_request_labels: crowdin
          pull_request_base_branch_name: "main"
          github_user_name: Crowdin Bot (Actions)
          github_user_email: support+bot@crowdin.com
          skip_ref_checkout: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          INPUT_CROWDIN_BRANCH_NAME: "i18n-crowdin-translations"
